apiVersion: v2
appVersion: 1.7.0
dependencies:
- name: common
  repository: file://charts/common
  version: 0.0.*
- alias: dbNamespace
  condition: dbNamespace.enabled
  name: everest-db-namespace
  repository: file://charts/everest-db-namespace
  version: 1.7.0
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.27.0
- alias: monitoring
  condition: monitoring.enabled
  name: victoria-metrics-operator
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.43.0
- condition: pmm.enabled
  name: pmm
  repository: https://percona.github.io/percona-helm-charts
  version: 1.3.*
description: A cloud-native database platform
kubeVersion: '>= 1.27.0-0'
maintainers:
- email: mayank.shah@percona.com
  name: mayankshah1607
- email: oksana.grishchenko@percona.com
  name: oksana-grishchenko
- email: diogo.recharte@percona.com
  name: recharte
name: everest
type: application
version: 1.7.0
