apiVersion: v2
appVersion: 1.7.0
dependencies:
- name: common
  repository: file://../common
  version: 0.0.*
description: A sub-chart for provisioning Everest DB namespaces.
kubeVersion: '>= 1.27.0-0'
maintainers:
- email: mayank.shah@percona.com
  name: mayankshah1607
- email: oksana.grishchenko@percona.com
  name: oksana-grishchenko
- email: diogo.recharte@percona.com
  name: recharte
name: everest-db-namespace
type: application
version: 1.7.0
